### PR TITLE
Set the app's version and name correctly in development

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes electron-userland/electron-forge/issues/258

### CODE REVIEW

**Comment by BenV** [comment]
Will this change also be effective in updating the user data and user cache paths? My super-hacky workaround for this issue also had to modify those based on the contents of package.json, otherwise they were set to `/Users/<username>/Application Support/Electron/...` etc. 

Sorry if the answer to this is obvious, I'm not super familiar with these repos. Thanks so much for the quick fix!

**Comment by malept** [comment]
Doesn't appear so.

@MarshallOfSound we may as well just copy/paste all of this? https://github.com/electron/electron/blob/d26e4a4abf9dfc277974c6c9678a24a5f9e4d104/default_app/main.js#L254-L272

**Comment by MarshallOfSound** [comment]
@malept That behavior is the same even for apps using the normal `electron` prebuilt package.  Paths for development electron apps are always set to `Electron`.

In fact, thinking about it, even the app name and version are set to "Electron" in the normal prebuilt.  I think this is "expected behavior" if we're going for mirroring `electron-prebuilt`.  If we want to change this it would be a breaking change (if we changes paths) and it should be done in the normal prebuilt module.

**Comment by malept** [comment]
@MarshallOfSound oh, I didn't realize that was the same behavior as `electron-prebuilt`. I am certainly not advocating breaking compatibility.

**Comment by MarshallOfSound** [comment]
Yeah I forgot that `electron-prebuilt` does this as well, closing this out.  If people feel this behavior should change raise an issue in the `electron-prebuilt` repository 👍

**Comment by BenV** [comment]
@MarshallOfSound - Hmm, testing this out quickly:

* With electron-prebuilt-compile@1.6.11:
`App: Electron, version: 1.6.11, userData: /Users/vinsonb/Library/Application Support/Electron`

* With electron@1.6.11:
`App: electron-quick-start, version: 1.0.0, userData: /Users/vinsonb/Library/Application Support/electron-quick-start`

It seems like `electron` does what I would expect, but maybe I'm confused about `electron` vs `electron-prebuilt` and you're talking about something different? It seems like electron-prebuilt-compile is reading the package.json from electron itself for all of this stuff instead of the app's package.json? Feel free to tell me to get out of your hair if I'm way off base, I don't want to be wasting anyone's time 😄

**Comment by MarshallOfSound** [comment]
Oh, so Electron sets the name / version internally correctly if you provide a directory to launch the app from (`.`) if you provide a file `main.js` it does not.

Now although users provide a directory to `electron-prebuilt-compile` it gets proxied into a path to `es6-init.js` internally so all reference to the original directory is lost.  So I think we should do what @malept mentioned and just copy-pasta that logic into `electron-prebuilt-compile` from Electron itself to set paths and names correctly.  Not sure if that's a breaking change considering it's technically a fix 💭

**Comment by paulcbetts** [comment]
❇️

**Comment by BenV** [comment]
Was it decided to just leave the app path functionality alone?

**Pull request merged**
